[package]
name = "perm-demo"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }