version: 2

multi-ecosystem-groups:
  global-rollup:
    schedule:
      interval: "weekly"
      day: "sunday"

updates:
  - package-ecosystem: "cargo"
    directory: "/" 
    multi-ecosystem-group: "global-rollup"

  - package-ecosystem: "nix"
    directory: "/"
    multi-ecosystem-group: "global-rollup"
