[workspace]
resolver = "2"
members = [
    "cli",
    "connector/cli",
    "connector/ws",
    "control-socket/tcp/client",
    "control-socket/tcp/server",
    "puppet",
    "supervisor/mock",
    "supervisor/qemu",
    "supervisor/nbd-netboot",
    "switchboard",
    "treadmill-rs",
    "switchboard-macros",
    "switchboard-traits", "supervisor/lib",
]

[workspace.package]
version = "0.1.0"
authors = ["Treadmill Project Developers <treadmill@tockos.org>"]
edition = "2021"
