#!/usr/bin/env bash

# Configuration
DB_URL="postgres://ben@localhost:5432/treadmill_dev"
SCHEMA_DIR="switchboard/sql/"
MIGRATIONS_DIR="switchboard/migrations"  # Directory where sqlx migrations live

# Create migrations directory if it doesn't exist
mkdir -p "$MIGRATIONS_DIR"

# Generate timestamp for migration name
TIMESTAMP=$(date +%Y%m%d%H%M%S)
MIGRATION_NAME="schema_diff_migration"
MIGRATION_PREFIX="${TIMESTAMP}_${MIGRATION_NAME}"

# Generate the plan and capture both stdout and stderr
echo "Generating migration plan..."
TEMP_PLAN_FILE="/tmp/pg_schema_diff_plan.txt"

# Clear existing schema
psql "$DB_URL" -c "DROP SCHEMA IF EXISTS tml_switchboard CASCADE;"

# Now generate the schema diff plan
pg-schema-diff plan --dsn "$DB_URL" --schema-dir "$SCHEMA_DIR" > "$TEMP_PLAN_FILE" 2>&1

# Extract DDL statements from the plan
echo "Extracting DDL statements..."
UP_MIGRATION_FILE="${MIGRATIONS_DIR}/${MIGRATION_PREFIX}.up.sql"
DOWN_MIGRATION_FILE="${MIGRATIONS_DIR}/${MIGRATION_PREFIX}.down.sql"

# Create UP migration with types defined first
{
    echo "-- Migration generated by pg-schema-diff"
    echo "-- Generated at: $(date)"
    echo
    echo "BEGIN;"
    echo
    echo "-- Create schema"
    echo "CREATE SCHEMA IF NOT EXISTS tml_switchboard;"
    echo
    echo "-- Create custom types first"
    echo "CREATE TYPE tml_switchboard.user_type AS ENUM ('normal', 'system');"
    echo
    echo "CREATE TYPE tml_switchboard.functional_state AS ENUM ("
    echo "    'queued',"
    echo "    'dispatched',"
    echo "    'finalized'"
    echo ");"
    echo
    echo "CREATE TYPE tml_switchboard.exit_status AS ENUM ("
    echo "    'supervisor_match_error',"
    echo "    'internal_supervisor_error',"
    echo "    'supervisor_host_start_error',"
    echo "    'supervisor_dropped_job',"
    echo "    'queue_timeout',"
    echo "    'job_timeout',"
    echo "    'job_canceled',"
    echo "    'workload_finished_success',"
    echo "    'workload_finished_error',"
    echo "    'workload_finished_unknown'"
    echo ");"
    echo
    echo "CREATE TYPE tml_switchboard.api_token_cancellation AS ("
    echo "    canceled_at timestamp with time zone,"
    echo "    cancellation_reason text"
    echo ");"
    echo
    echo "CREATE TYPE tml_switchboard.parameter_value AS ("
    echo "    value text,"
    echo "    is_secret boolean"
    echo ");"
    echo
    echo "CREATE TYPE tml_switchboard.restart_policy AS ("
    echo "    remaining_restart_count integer"
    echo ");"
    echo
    echo "-- Extract DDL statements from plan"
    grep "^[0-9]\+\. " "$TEMP_PLAN_FILE" | sed 's/^[0-9]\+\. //' | while read -r line; do
        # Extract the DDL part (everything before the first " -- ")
        ddl=$(echo "$line" | sed 's/ -- .*//')
        if [ ! -z "$ddl" ]; then
            echo "$ddl;"
        fi
    done
    echo
    echo "COMMIT;"
} > "$UP_MIGRATION_FILE"

# Create DOWN migration 
{
    echo "-- Down migration for ${MIGRATION_PREFIX}"
    echo "-- Generated at: $(date)"
    echo
    echo "BEGIN;"
    echo
    echo "DROP SCHEMA IF EXISTS tml_switchboard CASCADE;"
    echo
    echo "COMMIT;"
} > "$DOWN_MIGRATION_FILE"

# Clean up
rm "$TEMP_PLAN_FILE"
echo "Migration files generated:"
echo "UP: $UP_MIGRATION_FILE"
echo "DOWN: $DOWN_MIGRATION_FILE"
echo
echo "NOTE: Please review the generated migration files before applying them."
