[package]
name = "tml-puppet"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["transport_tcp", "transport_unix_seqpacket"]

transport_tcp = ["tml-tcp-control-socket-client"]
transport_unix_seqpacket = ["tml-unix-seqpacket-control-socket-client"]

[dependencies]
treadmill-rs = { path = "../treadmill-rs" }

tml-tcp-control-socket-client = { path = "../control-socket/tcp/client", optional = true }

anyhow = "1.0.76"
clap = { version = "4.4.11", features = ["derive"] }
simplelog = "0.12.1"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros", "fs", "sync", "process", "io-util", "time", "signal"] }
serde_json = "1.0.108"
log = "0.4.20"
nix = { version = "0.29.0", default-features = false, features = ["signal"] }

[target.'cfg(target_os = "linux")'.dependencies]
tml-unix-seqpacket-control-socket-client = { path = "../control-socket/unix-seqpacket/client", optional = true }
