[base]
supervisor_id = "7d55ec6d-15e7-4b84-8c04-7c085fe60df4"
coord_connector = "cli_connector"

[cli_connector]
# Doesn't do anything yet, but we require the images key to be present
images = { }

[mock]
max_parallel_jobs = 1