[base]
supervisor_id = "7d55ec6d-15e7-4b84-8c04-7c085fe60df4"
coord_connector = "cli_connector"

[cli_connector]
# Doesn't do anything yet, but we require the images key to be present
images = { }

[ws_connector]
private_key = "config/supervisors/7d55ec6d-15e7-4b84-8c04-7c085fe60df4/auth.pem"
switchboard_uri = "wss://localhost:443/supervisor"

[mock]
max_parallel_jobs = 1
