/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The board's console, as the host sees it.
 */
export type Console = {
  baud: number;
  /**
   * The host-side device node. Prefer a stable `/dev/serial/by-id/...`
   * path over a `/dev/ttyACM*` name, which is enumeration-order
   * dependent.
   */
  device: string;
  kind: "uart";
};
/**
 * The machine a host is, and the images it can boot.
 */
export type Platform =
  | {
      /**
       * The host's own CPU architecture, e.g. `aarch64`, `x86_64`.
       *
       * Redundant — a profile implies it — but kept so "any aarch64 host"
       * does not require enumerating profiles. Nothing enforces consistency
       * between the two.
       */
      arch: string;
      kind: "physical";
      model: string;
      /**
       * The whole machine configurations this host can boot, e.g.
       * `rpi4-uboot-sd`, `q35-virtio-uefi`, `q35-virtio-bios`,
       * `netboot-nbd`. A profile names a complete configuration the way a
       * target triple does; an image set member matches one by equality.
       *
       * An array because one host may genuinely serve several. Governed by
       * convention, not a registry.
       */
      profiles: string[];
      vendor: string;
    }
  | {
      /**
       * The architecture the guest is presented with.
       */
      arch: string;
      /**
       * e.g. `qemu`.
       */
      hypervisor: string;
      kind: "virtual";
      /**
       * As [`Platform::Physical::profiles`].
       */
      profiles: string[];
    };
/**
 * The `spec_version` discriminant of a [`HostSpecV2`] document.
 */
export type SpecVersionV2 = "v2";

/**
 * Version 2 of the host spec.
 */
export interface HostSpecV2 {
  /**
   * What this host is, in prose.
   */
  description?: string | null;
  /**
   * The devices under test wired to this host, in the order the operator
   * listed them. May be empty.
   */
  duts: DutV2[];
  /**
   * The host's GPIO controllers, keyed by a name the DUTs' pins refer to,
   * e.g. `rp1`. May be empty.
   */
  gpio_controllers: {
    [k: string]: GpioController;
  };
  /**
   * Must equal the `host_id` of the host this document describes.
   */
  id: string;
  /**
   * Operator-defined labels. CEL map indexing errors on an absent key, so
   * predicates guard with `'key' in host.labels`.
   */
  labels: {
    [k: string]: string;
  };
  /**
   * Where in the site, e.g. `rack4/shelf2`. Free text.
   */
  location?: string | null;
  /**
   * Display handle, e.g. `cam-rpi5-01`. Deliberately not unique; nothing
   * routes on it.
   */
  name: string;
  platform: Platform;
  resources: Resources;
  /**
   * The site the host lives at, e.g. `cambridge`. Flat, so a predicate reads
   * `host.site == 'cambridge'`.
   */
  site: string;
  spec_version: SpecVersionV2;
}
/**
 * One device under test wired to a host.
 */
export interface DutV2 {
  /**
   * The architectures of the board's cores, e.g. `cortex-m4`. An array
   * because a heterogeneous-core part has more than one. May be empty.
   */
  arch: string[];
  /**
   * The board this is, as a lowercase identifier, e.g. `nrf52840dk`.
   */
  board: string;
  /**
   * What the board can talk over, e.g. `ble`, `ieee802154`, `usb`, `wifi`,
   * `ethernet`, `can`. Governed by convention, not a registry. May be empty.
   */
  connectivity: string[];
  console?: Console | null;
  debug?: DebugAccess | null;
  /**
   * The board's pins wired to a GPIO controller, keyed by the board's own
   * pin name, e.g. `P0.13`. May be empty.
   */
  gpio: {
    [k: string]: GpioPin;
  };
  /**
   * As [`HostSpecV2::labels`], scoped to this DUT.
   */
  labels: {
    [k: string]: string;
  };
  /**
   * Display name, e.g. `nRF52840-DK`.
   */
  name?: string | null;
  /**
   * The board's **own** serial number, not its debug probe's.
   */
  serial?: string | null;
  vendor: string;
}
/**
 * How the board is programmed and debugged.
 */
export interface DebugAccess {
  probe: DebugProbe;
  /**
   * The wire protocol, e.g. `swd`, `jtag`. Governed by convention, not a
   * registry.
   */
  protocol: string;
}
/**
 * The debug probe attached to a board.
 */
export interface DebugProbe {
  /**
   * e.g. `J-Link OB`, `ST-LINK/V2-1`.
   */
  model: string;
  /**
   * The probe's own serial, which is how a host-side tool addresses it.
   */
  serial?: string | null;
  /**
   * e.g. `SEGGER`, `STMicroelectronics`.
   */
  vendor: string;
}
/**
 * One DUT pin wired to a host GPIO controller.
 */
export interface GpioPin {
  /**
   * Driver-specific settings that locate the pin on its controller.
   */
  config: {
    [k: string]: unknown;
  };
  /**
   * The key of the controller in `gpio_controllers`.
   */
  controller: string;
  /**
   * What the pin is for on the board, e.g. `LED1`, `BUTTON1`.
   */
  label?: string | null;
  /**
   * How the host may use the pin: `digital_in`, `digital_out`. Governed by
   * convention, not a registry.
   */
  modes: string[];
}
/**
 * A GPIO controller on the host, e.g. a SoC's pin controller or a USB GPIO
 * expander.
 */
export interface GpioController {
  /**
   * Driver-specific settings that locate the controller.
   */
  config: {
    [k: string]: unknown;
  };
  /**
   * How the host drives this controller, e.g. `linux-gpiochip`. Governed by
   * convention, not a registry.
   */
  driver: string;
}
/**
 * The ceiling available to a single job on this host.
 *
 * Unsigned, so CEL sees these as `uint`: comparisons against a plain literal
 * work (`host.resources.memory_mb >= 4096`), but arithmetic needs an unsigned
 * literal (`host.resources.memory_mb / 1024u >= 8`).
 */
export interface Resources {
  cpu_cores: number;
  memory_mb: number;
  storage_gb: number;
}
