[logs]
dir = "switchboard/logs"

[database]
address = "/home/leons/proj/treadmill/code/switchboard/switchboard/.nix-shell/db"
port = 5400
name = "tml_switchboard"

[database.auth]
PasswordAuth = { username = "leons", password = "" }

[public_server]
socket_addr = "0.0.0.0:8080"
cert = "config/tls-certs/localhost-public.pem"
key = "config/tls-certs/localhost.pem"

[websocket.auth]
per_message_timeout = "10s"

[api]
auth_session_timeout = "5m"
default_job_timeout = "30m"
