[logs]
dir = "switchboard/logs"

[database]
address = "localhost"
port = 5400
name = "tml_switchboard"

[database.auth]
PasswordAuth = { username = "postgres", password = "" }

[public_server]
socket_addr = "0.0.0.0:443"
cert = "config/tls-certs/localhost-public.pem"
key = "config/tls-certs/localhost.pem"

[internal_server]
socket_addr = "127.0.0.1:8430"
cert = ""
key = ""

[websocket.auth]
per_message_timeout = "10sec"

[api]
auth_presession_timeout = "5min"
auth_session_timeout = "5min"