[logs]
dir = "switchboard/logs"

[database]
host = "localhost"
port = 5400
name = "tml_switchboard"

[database.auth]
PasswordAuth = { username = "postgres", password = "" }

[server]
bind_address = "0.0.0.0:8080"

# Comment out this [server.dev_mode_ssl] table to disable dev-mode SSL
#[server.dev_mode_ssl]
#cert = "config/tls-certs/localhost-public.pem"
#key = "config/tls-certs/localhost.pem"

[api]
session_token_timeout = "5m"
default_job_timeout = "30m"
