[logs]
dir = "switchboard/logs"

[database]
address = "localhost"
port = 5400
name = "tml_switchboard"

[database.auth]
PasswordAuth = { username = "postgres", password = "" }

[server]
socket_addr = "0.0.0.0:443"

# Comment out this [server.dev_mode_ssl] table to disable dev-mode SSL
#[server.dev_mode_ssl]
#cert = "config/tls-certs/localhost-public.pem"
#key = "config/tls-certs/localhost.pem"

[websocket.auth]
per_message_timeout = "10s"

[api]
auth_session_timeout = "5m"
default_job_timeout = "30m"
