[logs]
dir = "switchboard/logs"

[database]
address = "localhost"
port = 5400
name = "tml_switchboard"

[database.auth]
PasswordAuth = { username = "postgres", password = "" }

[public_server]
socket_addr = "0.0.0.0:443"
cert = "switchboard/conf/tls-certs/cert.pem"
key = "switchboard/conf/tls-certs/key.pem"

[internal_server]
socket_addr = "127.0.0.1:8430"
cert = "switchboard/conf/tls-certs/cert_internal.pem"
key = "switchboard/conf/tls-certs/key_internal.pem"

[websocket.auth]
per_message_timeout = "10sec"

[api]
auth_presession_timeout = "5min"
auth_session_timeout = "5min"