[package]
name = "treadmill-rs"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.75"
serde = { version = "1.0.193", features = ["derive"] }
uuid = { version = "1.6.1", features = ["serde", "v4"] }
serde_with = { version = "3.8.1", features = ["hex", "base64"] }
subtle = "2.6.1"
chrono = { version = "0.4.38", features = ["serde"] }
fundu = { version = "2.0.0", features = ["chrono", "serde"] }
base64 = "0.22.1"
http = "1.1.0"
tml-switchboard-macros = { path = "../switchboard-macros" }
tml-switchboard-traits = { path = "../switchboard-traits" }
tracing = "0.1.40"