[package]
name = "treadmill-rs"
version = "0.2.0"
edition.workspace = true

authors.workspace = true
categories = ["api-bindings"]
description = "Common type- and API-definitions for the Treadmill distributed hardware testbed"
homepage = "https://treadmill.ci"
keywords = ["ci", "testing", "testbed", "hardware", "embedded"]
license = "MIT OR Apache-2.0"

[dependencies]
async-trait = "0.1.75"
serde = { version = "1.0.193", features = ["derive"] }
uuid = { version = "1.6.1", features = ["serde", "v4"] }
serde_with = { version = "3.8.1", features = ["hex", "base64"] }
subtle = "2.6.1"
chrono = { version = "0.4.38", features = ["serde"] }
fundu = { version = "2.0.0", features = ["chrono", "serde"] }
base64 = "0.22.1"
http = "1.1.0"
tracing = "0.1.40"