-- Modify "jobs" table
ALTER TABLE "tml_switchboard"."jobs" DROP CONSTRAINT "valid_image_id", DROP CONSTRAINT "valid_init_spec", ADD CONSTRAINT "valid_init_spec" CHECK (((resume_job_id IS NULL) AND ((((image_digest IS NOT NULL))::integer + ((image_group_digest IS NOT NULL))::integer) = 1)) OR ((resume_job_id IS NOT NULL) AND (restart_job_id IS NULL) AND (image_digest IS NULL) AND (image_group_digest IS NULL))), DROP COLUMN "image_id", ADD COLUMN "image_digest" text NULL, ADD COLUMN "image_group_digest" text NULL, ADD COLUMN "resolved_image_digest" text NULL;
-- Create "image_groups" table
CREATE TABLE "tml_switchboard"."image_groups" ("id" uuid NOT NULL, "index_digest" text NOT NULL, "owner_subject" uuid NULL, "label" text NULL, "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"), CONSTRAINT "image_groups_index_digest_key" UNIQUE ("index_digest"), CONSTRAINT "image_groups_owner_subject_fkey" FOREIGN KEY ("owner_subject") REFERENCES "tml_switchboard"."subjects" ("subject_id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "images" table
CREATE TABLE "tml_switchboard"."images" ("id" uuid NOT NULL, "manifest_digest" text NOT NULL, "artifact_type" text NOT NULL, "owner_subject" uuid NULL, "label" text NULL, "attrs" jsonb NOT NULL DEFAULT '{}', "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"), CONSTRAINT "images_manifest_digest_key" UNIQUE ("manifest_digest"), CONSTRAINT "images_owner_subject_fkey" FOREIGN KEY ("owner_subject") REFERENCES "tml_switchboard"."subjects" ("subject_id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "image_group_members" table
CREATE TABLE "tml_switchboard"."image_group_members" ("group_id" uuid NOT NULL, "image_id" uuid NOT NULL, "arch" text NOT NULL, "os" text NOT NULL, "variant" text NULL, "tml_target" text NULL, "tml_board" text NULL, PRIMARY KEY ("group_id", "image_id"), CONSTRAINT "image_group_members_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "tml_switchboard"."image_groups" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "image_group_members_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "tml_switchboard"."images" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "image_locations" table
CREATE TABLE "tml_switchboard"."image_locations" ("image_id" uuid NOT NULL, "registry" text NOT NULL, "repository" text NOT NULL, "status" text NOT NULL, "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("image_id", "registry", "repository"), CONSTRAINT "image_locations_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "tml_switchboard"."images" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "valid_location_status" CHECK (status = ANY (ARRAY['external'::text, 'canonical'::text, 'system'::text])));
