[package]
name = "tml-switchboard"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# For debugging reasons
console-subscriber = "0.4.0"

# Utility
uuid = { version = "1.9.1", features = ["serde", "fast-rng", "v4"] }
chrono = { version = "0.4.38", features = ["serde"] }
# because cookie-rs has an unavoidable hard dependency on time::Duration
time = "0.3.36"

# Database
sqlx = { version = "0.8.0", features = ["uuid", "runtime-tokio", "tls-rustls", "postgres", "macros", "chrono", "ipnetwork"] }

# Server
axum = { version = "0.7.5", features = ["tokio", "http2", "json", "tracing", "ws", "macros"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
headers = "0.4.0"
http = "1.1.0"
axum-server = { version = "0.7.1", features = ["tls-rustls"] }
tower-http = { version = "0.5.2", features = ["trace", "sensitive-headers"] }

# Tokio
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
futures-util = { version = "0.3.30", features = ["sink"] }

# Lock-free hashmap
dashmap = "6.0.1"

async-trait = "0.1.81"

# Used for token comparison
subtle = "2.6.1"
# Used for password verification
argon2 = { version = "0.6.0-pre.0", features = [] }
# CSPRNG
rand = { version = "0.9.0-alpha.1", features = ["getrandom"] }

# Logging facilities
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# Command line arguments
clap = { version = "4.5.8", features = ["derive", "error-context", "env"] }

# Configuration overlays
figment = { version = "0.10.19", features = ["toml", "env"] }

# XDG
xdg = "2.5.2"

# General serialization
serde = "1.0.204"
serde_json = "1.0.120"
# Configuration deserialization
toml = "0.8.14"
humantime-serde = "1.1.1"

# Error derives
thiserror = "1.0.61"
# TODO: Phase out
miette = { version = "7.2.0", features = ["fancy"] }
base64 = "0.21.7"

pin-project = "1.1.5"

treadmill-rs = { path = "../treadmill-rs" }
tml-switchboard-traits = { path = "../switchboard-traits" }

[dev-dependencies]
sqlx-cli = { version = "0.8.0", features = ["postgres", "rustls", "completions"] }