[package]
name = "tml-qemu-supervisor"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
treadmill-rs = { path = "../../treadmill-rs" }
tml-tcp-control-socket-server = { path = "../../control-socket/tcp/server" }
tml-cli-connector = { path = "../../connector/cli" }

tokio = { version = "1.35.1", default-features = false, features = ["rt-multi-thread", "process", "fs"] }
toml = "0.8.8"
uuid = "1.6.1"
serde = { version = "1.0.193", features = ["derive"] }
clap = { version = "4.4.11", features = ["derive"] }
simplelog = "0.12.1"
log = "0.4.20"
async-trait = "0.1.75"
anyhow = "1.0.76"
tempfile = "3.10.1"
strfmt = "0.2.4"
async-recursion = "1.1.1"
serde_json = "1.0.117"
