name: tml-static-checks
env:
  TERM: xterm # Makes tput work in actions output

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
  # To avoid double-runs, we only run checks on main (or other long-term
  # branches potentially added in the future). To initiate checks to be
  # triggered for a branch, open a (draft) PR.
  push:
    branches: [main]
  # Run CI for PRs on any branch
  pull_request:
  # Run CI for the GitHub merge queue
  merge_group:

# Cancel superseded runs for the same PR. Never cancel merge_group or main runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix flake check
        run: nix flake check --print-build-logs
