name: tml-static-checks
env:
  TERM: xterm # Makes tput work in actions output

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
  # Run CI for all branches except GitHub merge queue tmp branches
  push:
    branches-ignore:
    - "gh-readonly-queue/**"
  # Run CI for PRs on any branch
  pull_request:
  # Run CI for the GitHub merge queue
  merge_group:

permissions:
  contents: read

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix flake check
        run: nix flake check --print-build-logs
